### ISSUE TITLE
Can the name field multiple lines? 

### ISSUE THREAD

**Issue by fangxueliang1** [RonnyWeiss/Apex-D3-Organization-Chart#2]
I need multiple lines for the name field, how to set up in your plug in?

**Comment by RonnyWeiss** [comment]
did a carriage return work?

**Comment by fangxueliang1** [comment]
I used both \n and \r to try, they are not working

**Comment by RonnyWeiss** [comment]
Because of svg Text its Not possible at the Moment. I'd checked it sorry.
